### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Lucas-Martin2023** [Lucas-Martin2023/NeverForgetADate#15]
# User Story
As a user, I want a navigational bar to efficiently access different sections of the application, including viewing and adding events and dates, and the option to sign out.

# Acceptance Criteria
- [ ] Design and implement a responsive navigation bar that includes the following elements:
    - [ ] Application name
    - [ ] "View Events" button
    - [ ] "Add Event" button
    - [ ] "View Dates" button
    - [ ] "Add Date" button
    - [ ] "Sign Out" button
- [ ] Ensure the navigation bar is consistently visible across all pages of the application.
- [ ] Implement navigation functionality for each button, directing users to the corresponding sections of the application.
- [ ] Design the navigation bar for a pleasant and user-friendly visual experience.

# EXAMPLE

# Dependencies
User Authentication functionality must be completed.

# Dev Notes
- Make use of React Router to enable seamless navigation between different sections of the application.
- Ensure the design adheres to the overall theme and aesthetics of the application.
- Test the navigation bar thoroughly, checking both the functionality and appearance on different devices and browsers.

**Comment by bhavik001** [comment]
Hello @Lucas-Martin2023 !
I am interested in working on this application. Can you assign me this issue!
